blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

sw33tp0t4t0/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static
from django.utils.translation import gettext_lazy as _

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from tinymce import models as tinymce_models

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,unique_for_date='publish')
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
    body = tinymce_models.HTMLField()
    # body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')
    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.
    tags = TaggableManager()
    image = models.ImageField(upload_to='posts/%Y/%m', blank=True)

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

class ImagePost(models.Model):
    post=models.ForeignKey(Post, on_delete=models.CASCADE)
    image=models.ImageField(upload_to='posts/%Y/%m/')

blog/forms.py
from django import forms
from django.forms.widgets import Textarea
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=Textarea())


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Name', 'tabindex': 1}),
            'email': forms.TextInput(attrs={'placeholder': 'Email', 'tabindex': 2}),
            'body': forms.Textarea(attrs={'placeholder': 'Enter message...', 'tabindex': 3}),
        }


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.db.models import Count
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator, EmptyPage,\
                                  PageNotAnInteger
from django.core.mail import send_mail
from django.views.generic import ListView
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.postgres.search import TrigramSimilarity
from .models import Post, Comment, ImagePost
from .forms import EmailPostForm, CommentForm, SearchForm
from taggit.models import Tag
from django.http import HttpResponseRedirect
from django.urls import reverse

def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 5) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request,
                 'blog/post/list.html',
                 {'page': page,
                  'posts': posts,
                  'tag': tag})


def post_detail(request, post):
    post = get_object_or_404(Post, slug=post, status='published')
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
            return HttpResponseRedirect(reverse('blog:post_detail', args=[post.slug]))
    else:
        comment_form = CommentForm()

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
                                  .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                .order_by('-same_tags','-publish')[:4]

    image_list = ImagePost.objects.filter(post=post)

    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'image_list': image_list,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.published.annotate(
                similarity=TrigramSimilarity('title', query),
            ).filter(similarity__gt=0.1).order_by('-similarity')
    return render(request,
                  'blog/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
{% load icons %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/font.css' %}" />
  <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"  integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous"> 
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>
<body>
  <div class="container">
    <div class="column col-one">
        <div class="header">
            <h1><a href="{% url 'blog:post_list' %}">sw33tp0t4t0</a></h1>
        </div>

        <div class="nav-bar">
            <!-- <div class="search-form">
                <form>
                    <input type="search" placeholder="Search with title...">
                </form>
            </div> -->
        
            <div class="list-post">
                <ol>
                  {% get_most_commented_posts as most_commented_posts %}
                  {% for p in most_commented_posts %}
                    <li>
                      <a href="{{ p.get_absolute_url }}" {% if p.id == post.id %}class="active"{% endif %}>
                        {% icon 'bomb' %}&#8201;&#8201;&#8201;{{ p.title }}
                      </a>
                    </li>
                  {% endfor %}
                </ol>
            </div>
        </div>

        <div class="footer">
          Copyright © 2021
        </div>
    </div>

    <div class="column col-two">
      <!-- Top Navigation Menu -->
      <div class="topnav">
        <a href="{% url 'blog:post_list' %}" class="active">sw33tp0t4t0
          <!-- <div class="search-form">
            <form>
                <input type="search" placeholder="Search">
            </form>
        </div> -->
        </a>
        <div id="myLinks">
          {% get_most_commented_posts as most_commented_posts %}
          {% for p in most_commented_posts %}
            <a href="{{ p.get_absolute_url }}" {% if p.id == post.id %}class="active"{% endif %}>
              {% icon 'book' %} {{ p.title }}
            </a>
          {% endfor %}
        </div>
        <a href="javascript:void(0);" class="icon" onclick="myFunction()">{% icon 'bars' %}</a>
      </div>

      <script>
        function myFunction() {
          var x = document.getElementById("myLinks");
          if (x.style.display === "block") {
            x.style.display = "none";
          } else {
            x.style.display = "block";
          }
        }
        </script>
      <div class="main-content">
        <div id="content">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>

    <div class="column col-three">
      <div class="comment-box">
      
      </div>
    </div>
  </div>
  
</body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load icons %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h2>{{ post.title }}</h2>
    <div class="post-list-small">
        <i>
        <!-- tags -->
        {% icon 'tag' %}
        {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>{% if not forloop.last %}, {% endif %}
        {% endfor %}
        <!-- published date -->
        &#8201;&#8201; {% icon 'calendar' %} {{ post.publish|date:'H:i:s F d, Y' }}
        </i>
    </div>

    {{ post.body|markdown }}
    <!-- <p><a href="{% url 'blog:post_share' post.id %}">Share this post</a></p> -->

    {% with comments.count as total_comments %}
        <h3>{{ total_comments }} comment{{ total_comments|pluralize }}</h3>
    {% endwith %}

    {% if new_comment %}
        <h3>Your comment has been added.</h3>
    {% else %}
        <form id="comment-form" class="cf" method="post">
            {% csrf_token %}
            {{ comment_form.name.errors }}
            {{ comment_form.email.errors }}
            {{ comment_form.body.errors }}
            <div class="half left cf">
                {{comment_form.name}}
                {{comment_form.email}}
                <input type="submit" id="input-submit" value="Send Message" tabindex="4">
            </div>
            <div class="half right cf">
                {{comment_form.body}}
            </div>
        </form>
    {% endif %}

    {% for comment in comments %}
        <b>{{ comment.name }}</b> on {{ comment.created }}
        <div class="dialogbox">
            <div class="body">
                <span class="tip tip-up"></span>
                <div class="message">
                <span>{{ comment.body }}</span>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
  {% for post in latest_posts %}
    <li>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load icons %}

{% block title %}sw33tp0t4t0{% endblock %}

{% block content %}
    <!-- search post with tag -->
    {% if tag %}<h2>Posts tagged with "{{ tag.name }}"</h2>{% endif %}

    <!-- post list -->
    {% for post in posts %}
        <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
        <div class="post-list-small">
            <i>
                <!-- tags -->
                {% icon 'tag' %}
                {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>{% if not forloop.last %}, {% endif %}
                {% endfor %}
                <!-- published date -->
                &#8201;&#8201; {% icon 'calendar' %} {{ post.publish|date:'H:i:s F d, Y' }}
            </i>
        </div>

        <!-- sort post description -->
        <div class="post-list-sort-description">{{ post.body|markdown|truncatewords_html:50|safe }}</div>
    {% endfor %}

    <!-- pagination -->
    {% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Search{% endblock %}

{% block content %}
  {% if query %}
    <h1>Posts containing "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
          Found {{ total_results }} result{{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
        <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
        {{ post.body|markdown|truncatewords_html:5 }}
    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
    <p><a href="{% url "blog:post_search" %}">Search again</a></p>
  {% else %}
    <h1>Search for posts</h1>
    <form method="get">
      {{ form.as_p }}
      <input type="submit" value="Search">
    </form>
  {% endif %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
  {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
      "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Send e-mail">
    </form>
  {% endif %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
      <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
  </span>
</div>